jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - deps-{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.m2
            - ~/.coursier/cache
          key: deps-{{ checksum "build.sbt" }}

      # run tests!
      - run: sbt test
